#!/bin/bash

WORKDIR=$HOME/work/waas
GITHUB=https://github.com/hokendohjin/

ARRAY=( waasdev-admin-fe \
	waasdev-admin-be \
	waasdev-user-fe \
	waasdev-user-be \
	waasdev-ios \
	waasdev-android
)

for i in ${ARRAY[@]}
do
  cd ${WORKDIR}
  echo ${GITHUB}${i}.git
  if [ ! -e ${i} ]
  then
    echo "${i} clone"
    git clone ${GITHUB}${i}.git
  else
    echo "${i} fetch"
    cd ${i}
    git fetch
    git checkout master
    git pull
fi
done

